### ISSUE TITLE
cannot work

### ISSUE THREAD

**Issue by mithuncoder** [KhanhNguyen9872/deobf_pyobfuscate.com#1]
cannot work..if i run the script.it will automatically closing and cannot find the error.if i open the script in interpreter cannot open..so much lag.im using try except it will show bad marshal data..my python version is 3.11

**Comment by KhanhNguyen9872** [comment]
> cannot work..if i run the script.it will automatically closing and cannot find the error.if i open the script in interpreter cannot open..so much lag.im using try except it will show bad marshal data..my python version is 3.11

can you give me a video? and please do look like tutorial, code will not work except have obfuscate variable with data

**Comment by KhanhNguyen9872** [comment]
> cannot work..if i run the script.it will automatically closing and cannot find the error.if i open the script in interpreter cannot open..so much lag.im using try except it will show bad marshal data..my python version is 3.11

Gif tutorial now available in README

**Comment by mithuncoder** [comment]
> Gif tutorial now available in README

why u cant give original deobfuscate source code.

**Comment by KhanhNguyen9872** [comment]
> > Gif tutorial now available in README
> 
> why u cant give original deobfuscate source code.

Not available right now! Someone will steal my code for commercial use
