### ISSUE TITLE
obf

### ISSUE THREAD

**Issue by mithuncoder** [KhanhNguyen9872/deobf_pyobfuscate.com#11]
how to deobfuscate this file

https://pyobfuscate.com/pyd/aes.txt

**Comment by KhanhNguyen9872** [comment]
> how to deobfuscate this file
> 
> https://pyobfuscate.com/pyd/aes.txt

new version no longer use this file, skip it

**Comment by mithuncoder** [comment]
Can u give me the old deobfuscator

**Comment by KhanhNguyen9872** [comment]
> Can u give me the old deobfuscator

previous version [here](https://github.com/KhanhNguyen9872/deobf_pyobfuscate.com/tree/9c75d15ddbf28c7272663ecea785393c0cf63e4c)
you can get it in commit

**Comment by mithuncoder** [comment]
I want that  lambda deobfuscator like a underscore obfuscation.


_____=lambda _:type(*_);_0_=str;___=dict;_0=lambda _0:_0.__code__.co_argcount;_=None;_

**Comment by mithuncoder** [comment]
new version deobfuscator not working..its look like new obfusaction..please check new obfuscate.
https://pyobfuscate.com/pyd

**Comment by KhanhNguyen9872** [comment]
> new version deobfuscator not working..its look like new obfusaction..please check new obfuscate. https://pyobfuscate.com/pyd

you are a author of this web? trying to make me give you how to deobf this??? i know in new obf of this web only have this, deobf this and will have full of code
![image](https://github.com/user-attachments/assets/4a973d54-7191-498f-af54-5ee08ba6bedc)

**Comment by KhanhNguyen9872** [comment]
> new version deobfuscator not working..its look like new obfusaction..please check new obfuscate. https://pyobfuscate.com/pyd

updated

**Comment by KhanhNguyen9872** [comment]
> new version deobfuscator not working..its look like new obfusaction..please check new obfuscate. https://pyobfuscate.com/pyd

Stop trying to detect, i have too much method to bypass it and you can't detect it, buy in old version, currently you can't block it

![image](https://github.com/user-attachments/assets/5d0d0d56-5315-4c05-a5f7-912530628a7d)

**Comment by cemiritireng** [comment]
> > new version deobfuscator not working..its look like new obfusaction..please check new obfuscate. https://pyobfuscate.com/pyd
> 
> you are a author of this web? trying to make me give you how to deobf this??? i know in new obf of this web only have this, deobf this and will have full of code ![image](https://github.com/user-attachments/assets/4a973d54-7191-498f-af54-5ee08ba6bedc)



How do I deobf this?
