### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Ucill924** [KhanhNguyen9872/deobf_pyobfuscate.com#17]
do you have twitter?

**Comment by KhanhNguyen9872** [comment]
> do you have twitter?

not
please write your help to here

**Comment by Ucill924** [comment]
hep to dekrip a skrip but
i cant write here coz the skrip is too long ?

**Comment by KhanhNguyen9872** [comment]
> hep to dekrip a skrip but i cant write here coz the skrip is too long ?

you can upload file to comment, just rename it to .txt and drag to input comment
or upload it to temp.sh

**Comment by Ucill924** [comment]
[bot.txt](https://github.com/user-attachments/files/17380581/bot.txt)


pleaase help how to decrypt this

**Comment by KhanhNguyen9872** [comment]
> [bot.txt](https://github.com/user-attachments/files/17380581/bot.txt)
> 
> pleaase help how to decrypt this

tutorial for old version found here: https://github.com/KhanhNguyen9872/deobf_pyobfuscate.com/issues/15#issuecomment-2402029564

**Comment by KhanhNguyen9872** [comment]
here is your result
[result.txt](https://github.com/user-attachments/files/17380776/result.txt)

**Comment by Ucill924** [comment]
thank you i tried follow the tutrorial but alwats got erors

**Comment by Ucill924** [comment]
![image](https://github.com/user-attachments/assets/06417cc6-ca7d-4c7b-bd83-6f6e40363c56)


this right steps to decrypt right ?

**Comment by KhanhNguyen9872** [comment]
> ![image](https://private-user-images.githubusercontent.com/72456107/376724565-06417cc6-ca7d-4c7b-bd83-6f6e40363c56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMzU5NjEsIm5iZiI6MTcyOTAzNTY2MSwicGF0aCI6Ii83MjQ1NjEwNy8zNzY3MjQ1NjUtMDY0MTdjYzYtY2E3ZC00YzdiLWJkODMtNmY2ZTQwMzYzYzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIzNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTkwM2YzMzc1ZWU2NjBlZDE2MzNmMWI0MmZmMjE0YmY3NGNlY2EzNzg2OGRmZTIxNzUxOWFlYTc5YjU2MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xUWzoaQECsWBG9e-kfPtreSUYUmG44iTJLqKbhQvSYk)
> 
> this right steps to decrypt right ?

sure
if you got error by missing library, try install library first

**Comment by Ucill924** [comment]
thank you, I've solved it, I was confused when I decrypted it and it was still a readable script, it turned out it took two time  decrypts

**Comment by KhanhNguyen9872** [comment]
> thank you, I've solved it, I was confused when I decrypted it and it was still a readable script, it turned out it took two time decrypts

yes, this script was obfuscate two times

**Comment by Ucill924** [comment]
[t.txt](https://github.com/user-attachments/files/18290064/t.txt)

can you dekrip this one bro
