### ISSUE TITLE
If somebody obfuscate the source code more than 1 times , this deobfuscate won't work. 

### ISSUE THREAD

**Issue by gfggfdffhdfhd** [KhanhNguyen9872/deobf_pyobfuscate.com#20]
If somebody obfuscate the source code more than 1 times , this deobfuscate won't work. Pls make some changes to deobfuscate 2 times obfuscated code.

**Comment by KhanhNguyen9872** [comment]
> If somebody obfuscate the source code more than 1 times , this deobfuscate won't work. Pls make some changes to deobfuscate 2 times obfuscated code.

just deobfuscate two times
