### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by tas33n** [KhanhNguyen9872/deobf_pyobfuscate.com#21]
i tried with this file https://raw.githubusercontent.com/MahiroDev091/EAAA-EAAD-EAAD6V7-TOKEN-GETTER/refs/heads/main/token.py but it only returns 
'pip install requests \npress enter to Exit' this line.

![image](https://github.com/user-attachments/assets/3f5b5eaa-2b3c-4c19-bb61-19fce5f5e4a1)

**Comment by KhanhNguyen9872** [comment]
> i tried with this file https://raw.githubusercontent.com/MahiroDev091/EAAA-EAAD-EAAD6V7-TOKEN-GETTER/refs/heads/main/token.py but it only returns 'pip install requests \npress enter to Exit' this line.
> 
> ![image](https://private-user-images.githubusercontent.com/55633040/385632892-3f5b5eaa-2b3c-4c19-bb61-19fce5f5e4a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODc3OTIsIm5iZiI6MTczMTQ4NzQ5MiwicGF0aCI6Ii81NTYzMzA0MC8zODU2MzI4OTItM2Y1YjVlYWEtMmIzYy00YzE5LWJiNjEtMTlmY2U1ZjVlNGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA4NDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzY2Q3MzA0MTM2ZmFmMWU5MTkxMjJlZmEyOGVmN2JhMmJiZjkzYzI5MDRmMjcxZGM2ZDlmMzhkMjE1NzQ2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ey3Ngqt2FlxiIkzuZbAe31I7SwKUm6mD7rgBte4ftEk)

this is very old pyobfuscate, please using old version, current version only work on latest script
