### ISSUE TITLE
deobfuscator problem, with pip packages

### ISSUE THREAD

**Issue by runtimefailure** [KhanhNguyen9872/deobf_pyobfuscate.com#22]
im trying to get back my old booster code which is obfuscated with that shit
but the problem is that it does not wanna use my system packages
and becouse of that my app is trying to install that package and it exists
in result not giving my app code is there any fix for this?

bellow i put screenshot of that.
![image](https://github.com/user-attachments/assets/df366952-238d-4dd1-a69d-a241d48ac530)

**Comment by KhanhNguyen9872** [comment]
> im trying to get back my old booster code which is obfuscated with that shit but the problem is that it does not wanna use my system packages and becouse of that my app is trying to install that package and it exists in result not giving my app code is there any fix for this?
> 
> bellow i put screenshot of that. ![image](https://private-user-images.githubusercontent.com/91615271/388921679-df366952-238d-4dd1-a69d-a241d48ac530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDI3MDgsIm5iZiI6MTczMjMwMjQwOCwicGF0aCI6Ii85MTYxNTI3MS8zODg5MjE2NzktZGYzNjY5NTItMjM4ZC00ZGQxLWE2OWQtYTI0MWQ0OGFjNTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE5MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YTUxMzZjZmRmNTk4ZTc5NDVlZWFjNWQ1ZjZlYjRkMDQ5NTIwZjE2ZjIyYjNkMzk1NTU0YTk3MmNhNTFkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.77t8MaU5E3fTmWyCLzGXjAZRmDa_bmvXiiWzUeEf7WQ)

give me your file, or you can try old version in README.md

**Comment by runtimefailure** [comment]
https://file.io/Yfd5tZidU7Qc

**Comment by KhanhNguyen9872** [comment]
> https://file.io/Yfd5tZidU7Qc

![image](https://github.com/user-attachments/assets/ca004224-ef8c-4170-b3d2-983942ebaab1)
this file using 26-10-2023 version

**Comment by runtimefailure** [comment]
k i just used de4py its faster and so much better
