### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by mukuluku** [KhanhNguyen9872/deobf_pyobfuscate.com#6]
I have only this:

_ = lambda __ : __import__('zlib').decompress(__import__('base64').b64decode(__[::-1]));exec((_)(string here))

How can I get the original code? Thanks!

**Comment by KhanhNguyen9872** [comment]
> I have only this:
> 
> _ = lambda __ : **import**('zlib').decompress(**import**('base64').b64decode(__[::-1]));exec((_)(string here))
> 
> How can I get the original code? Thanks!

need file

**Comment by mukuluku** [comment]
> > I have only this:
> > _ = lambda __ : **import**('zlib').decompress(**import**('base64').b64decode(__[::-1]));exec((_)(string here))
> > How can I get the original code? Thanks!
> 
> need file

I can send you the file, there's no problem with that. Just give me a contact. Although I would like to understand how your code works and try to solve it on my own.

**Comment by KhanhNguyen9872** [comment]
> I have only this:
> 
> _ = lambda __ : **import**('zlib').decompress(**import**('base64').b64decode(__[::-1]));exec((_)(string here))
> 
> How can I get the original code? Thanks!

```python
import time
def abc(p):
    print(p)
    time.sleep(0.5)
    return p
    
_ = lambda __ : abc(__import__('zlib').decompress(__import__('base64').b64decode(__[::-1])))

exec((_)(string here))
```
