### ISSUE TITLE
i just dont get it working with latest pyobfuscator, is there an update?

### ISSUE THREAD

**Issue by Awzum731** [KhanhNguyen9872/deobf_pyobfuscate.com#7]
hey man, dont get it working with latest pyobfuscator files. also some lines in ur files are now called pyobfuscate and not obfuscate? can u check m8

also there is a crypto import now required it says for me?
maybe u can update to a example with latest pyobfus. ty

**Comment by KhanhNguyen9872** [comment]
> hey man, dont get it working with latest pyobfuscator files. also some lines in ur files are now called pyobfuscate and not obfuscate? can u check m8
> 
> also there is a crypto import now required it says for me? maybe u can update to a example with latest pyobfus. ty

tested in 01/05/2024, i was try obf a hello world and it working for now, why you can't get it work? please send me your error and your obf file

**Comment by Awzum731** [comment]
C:\Users\Unknown\Downloads\deobf_pyobfuscate.com-main (1)\deobf_pyobfuscate.com-main\example>python deobf_run_this_to_get_code.py
Requirement already satisfied: pycryptodome in c:\users\unknown\appdata\local\programs\python\python311\lib\site-packages (3.20.0)
ERROR:root:Traceback (most recent call last):
  File "<KhanhNguyen9872>", line 75, in <module>
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<KhanhNguyen9872>", line 115, in <module>
ModuleNotFoundError: No module named 'Crypto'

all crypto installs are done
