### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by vedma1337** [KhanhNguyen9872/deobf_pyobfuscate.com#8]
Unable to create process using 'C:\bin\python3 "C:\Users\Administrator\Desktop\deobf_pyobfuscate.com-main\pyd_pyobf_deobf.py" ': The system cannot find the file specified.

**Comment by KhanhNguyen9872** [comment]
> Unable to create process using 'C:\bin\python3 "C:\Users\Administrator\Desktop\deobf_pyobfuscate.com-main\pyd_pyobf_deobf.py" ': The system cannot find the file specified.

please run python script using `python` command on your system, did you know how to run python script?
